caption: Wilco DTC configuration
deprecated: true
desc: |-
  Setting the policy configures the <ph name="WILCO_NAME">wilco</ph> diagnostics and telemetry controller (DTC), if available on the device. The setup size can't exceed 1MB (1,000,000 bytes) and must be in JSON format. The <ph name="WILCO_NAME">wilco</ph> DTC is responsible for handling it. The cryptographic hash verifies the integrity of the download. The configuration is downloaded and cached. It's redownloaded whenever the URL or the hash changes.

        If you set this policy, users can't change it.
device_only: true
example_value:
  hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
  url: https://example.com/wilcodtcconfig
features:
  dynamic_refresh: true
  per_profile: false
max_size: 1000000
owners:
- bkersting@google.com
- kerker@chromium.org
- chungsheng@google.com
- byronlee@chromium.org
- chromeos-oem-services@google.com
schema:
  properties:
    hash:
      type: string
    url:
      type: string
  type: object
supported_on:
- chrome_os:75-122
tags: []
type: external
generate_device_proto: False
