arc_support: Only a subset of proxy configuration options are made available to Android
  apps. Android apps may voluntarily choose to use the proxy. You cannot force them
  to use a proxy.
caption: Proxy settings
desc: |-
  Setting the policy configures the proxy settings for Chrome and ARC-apps, which ignore all proxy-related options specified from the command line.

         Leaving the policy unset lets users choose their proxy settings.

         Setting the <ph name="PROXY_SETTINGS_POLICY_NAME">ProxySettings</ph> policy accepts the following fields:
           * <ph name="PROXY_MODE_PROXY_SETTINGS_FIELD">ProxyMode</ph>, which lets you specify the proxy server Chrome uses and prevents users from changing proxy settings
           * <ph name="PROXY_PAC_URL_PROXY_SETTINGS_FIELD">ProxyPacUrl</ph>, a URL to a proxy .pac file, or a PAC script encoded as a data URL with MIME type application/x-ns-proxy-autoconfig
           * <ph name="PROXY_PAC_MANDATORY_PROXY_SETTINGS_FIELD">ProxyPacMandatory</ph>, which prevents the network stack from falling back to direct connections with invalid or unavailable PAC script
           * <ph name="PROXY_SERVER_PROXY_SETTINGS_FIELD">ProxyServer</ph>, a URL of the proxy server
           * <ph name="PROXY_BYPASS_LIST_PROXY_SETTINGS_FIELD">ProxyBypassList</ph>, a list of hosts for which the proxy will be bypassed

         The <ph name="PROXY_SERVER_MODE_PROXY_SETTINGS_FIELD">ProxyServerMode</ph> field is deprecated in favor of the <ph name="PROXY_MODE_PROXY_SETTINGS_FIELD">ProxyMode</ph> field.

          For <ph name="PROXY_MODE_PROXY_SETTINGS_FIELD">ProxyMode</ph>, if you choose the value:
            * <ph name="PROXY_MODE_ENUM_DIRECT">direct</ph>, a proxy is never used and all other fields are ignored.
            * <ph name="PROXY_MODE_ENUM_SYSTEM">system</ph>, the systems's proxy is used and all other fields are ignored.
            * <ph name="PROXY_MODE_ENUM_AUTO_DETECT">auto_detect</ph>, all other fields are ignored.
            * <ph name="PROXY_MODE_ENUM_FIXED_SERVERS">fixed_servers</ph>, the <ph name="PROXY_SERVER_PROXY_SETTINGS_FIELD">ProxyServer</ph> and <ph name="PROXY_BYPASS_LIST_PROXY_SETTINGS_FIELD">ProxyBypassList</ph> fields are used.
            * <ph name="PROXY_MODE_ENUM_PAC_SCRIPT">pac_script</ph>, the <ph name="PROXY_BYPASS_LIST_PROXY_PAC_URL">ProxyPacUrl</ph>, <ph name="PROXY_PAC_MANDATORY_PROXY_SETTINGS_FIELD">ProxyPacMandatory</ph> and <ph name="PROXY_BYPASS_LIST_PROXY_SETTINGS_FIELD">ProxyBypassList</ph> fields are used.

        Note: For more detailed examples, visit The Chromium Projects ( https://www.chromium.org/developers/design-documents/network-settings#TOC-Command-line-options-for-proxy-sett ).
example_value:
  ProxyBypassList: https://www.example1.com,https://www.example2.com,https://internalsite/
  ProxyMode: fixed_servers
  ProxyServer: 123.123.123.123:8080
features:
  dynamic_refresh: true
  per_profile: true
future_on:
- fuchsia
owners:
- acostinas@google.com
- file://components/proxy_config/OWNERS
schema:
  properties:
    ProxyBypassList:
      type: string
    ProxyMode:
      enum:
      - direct
      - auto_detect
      - pac_script
      - fixed_servers
      - system
      type: string
    ProxyPacMandatory:
      type: boolean
    ProxyPacUrl:
      type: string
    ProxyServer:
      type: string
    ProxyServerMode:
      $ref: ProxyServerMode
  type: object
supported_on:
- chrome.*:18-
- chrome_os:18-
- android:30-
tags:
- system-security
type: dict
