caption: Site search settings
desc: |-
  This policy provides a list of sites that users can quickly search using shortcuts in the address bar. Users can initiate a search by typing the shortcut or @shortcut (e.g. @work), followed by Space or Tab, in the address bar.

  The following fields are required for each site: <ph name="NAME_SITE_SEARCH_SETTINGS_FIELD">name</ph>, <ph name="SHORTCUT_SITE_SEARCH_SETTINGS_FIELD">shortcut</ph>, <ph name="URL_SITE_SEARCH_SETTINGS_FIELD">url</ph>.

  The <ph name="NAME_SITE_SEARCH_SETTINGS_FIELD">name</ph> field corresponds to the site or search engine name to be shown to the user in the address bar.

  The <ph name="SHORTCUT_SITE_SEARCH_SETTINGS_FIELD">shortcut</ph> can include plain words and characters, but cannot include spaces or start with the @ symbol. Shortcuts must also be unique.

  For each entry, the <ph name="URL_SITE_SEARCH_SETTINGS_FIELD">url</ph> field specifies the URL of the search engine used during a search with the corresponding keyword. The URL must include the string <ph name="SEARCH_TERM_MARKER">'{searchTerms}'</ph>, replaced in the query by the user's search terms. Invalid entries and entries with duplicate shortcuts are ignored.

  Site search entries configured as featured are displayed in the address bar when the user types "@". Up to three entries can be selected as featured.

  For a site search entry where <ph name="ALLOW_USER_OVERRIDE_SITE_SEARCH_SETTINGS_FIELD">allow_user_override</ph> is true, users have the ability to edit or disable that entry. However, featured engines (beginning with "@") can only be disabled. If a user modifies an entry that was initially created by this policy, it will no longer be managed by policy and will be treated like a user-created shortcut. When <ph name="ALLOW_USER_OVERRIDE_SITE_SEARCH_SETTINGS_FIELD">allow_user_override</ph> is false or unspecified for a site search entry, users cannot edit or disable that entry. The setting to allow user override is only supported on M139 and later; earlier versions will default to disabling user override.

  Users cannot create new site search entries with a shortcut previously created via this policy unless <ph name="ALLOW_USER_OVERRIDE_SITE_SEARCH_SETTINGS_FIELD">allow_user_override</ph> is set to true for the site search entry.

  In case of a conflict with a shortcut previously created by the user, the user setting takes precedence. However, users can still trigger the option created by the policy by typing "@" in the search bar. For example, if the user already defined "work" as a shortcut to URL1 and the policy defines "work" as a shortcut to URL2, then typing "work" in the search bar will trigger a search to URL1, but typing "@work" in the search bar will trigger a search to URL2.

  On <ph name="MS_WIN_NAME">Microsoft® Windows®</ph>, this policy is only available on instances that are joined to a <ph name="MS_AD_NAME">Microsoft® Active Directory®</ph> domain, joined to <ph name="MS_AAD_NAME">Microsoft® Azure® Active Directory®</ph> or enrolled in <ph name="CHROME_ENTERPRISE_CORE_NAME">Chrome Enterprise Core</ph>.

  On <ph name="MAC_OS_NAME">macOS</ph>, this policy is only available on instances that are managed via MDM, joined to a domain via MCX or enrolled in <ph name="CHROME_ENTERPRISE_CORE_NAME">Chrome Enterprise Core</ph>.

example_value:
- featured: true
  name: Google Wikipedia
  shortcut: wikipedia
  url: https://www.google.com/search?q=site%3Awikipedia.com+%s
- name: YouTube
  shortcut: youtube
  url: https://www.youtube.com/results?search_query=%s
- name: Google Drive
  shortcut: drive
  url: https://drive.google.com/?q=%s
  allow_user_override: true
features:
  dynamic_refresh: true
  per_profile: true
owners:
- ftirelo@chromium.org
- pastarmovj@chromium.org
schema:
  type: array
  items:
    type: object
    properties:
      featured:
        type: boolean
      name:
        type: string
      shortcut:
        type: string
      url:
        type: string
      allow_user_override:
        type: boolean
    required:
    - shortcut
    - name
    - url
sensitive: true
supported_on:
- chrome.*:128-
- chrome_os:128-
tags: []
type: dict
