caption: Configures System-proxy service for <ph name="PRODUCT_OS_NAME">$2<ex>Google
  ChromeOS</ex></ph>.
desc: |-
  Configures the availability of System-proxy service and the proxy credentials for system services.
        If the policy is not set, System-proxy service will not be available.
device_only: true
example_value:
  policy_credentials_auth_schemes:
  - basic
  - ntlm
  system_proxy_enabled: true
  system_services_password: '0000'
  system_services_username: test_user
features:
  dynamic_refresh: true
  per_profile: false
owners:
- acostinas@google.com
schema:
  properties:
    policy_credentials_auth_schemes:
      description: |-
        The authentication schemes for which the policy credentials can be applied. Can be one of:
                    * basic
                    * digest
                    * ntlm
                    Leaving this option empty will allow all three schemes to be used.
      items:
        enum:
        - basic
        - digest
        - ntlm
        type: string
      type: array
    system_proxy_enabled:
      type: boolean
    system_services_password:
      description: The password for authenticating system services to the remote web
        proxy.
      sensitiveValue: true
      type: string
    system_services_username:
      description: The username for authenticating system services to the remote web
        proxy.
      sensitiveValue: true
      type: string
  type: object
supported_on:
- chrome_os:87-
tags: []
type: dict
generate_device_proto: False
