caption: Allow the user to manage VPN connections
desc: |-
  Setting the policy to Enabled or leaving it unset lets users manage (disconnect or modify) VPN connections. If the VPN connection is created using a VPN app, the UI inside the app isn't affected. So, users might still be able to use the app to modify the VPN connection. Use this policy with the Always on VPN feature, which lets the admin decide to establish a VPN connection when starting a device.

        Setting the policy to Disabled turns off the <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> user interfaces that would let the user disconnect or modify VPN connections.
example_value: false
features:
  dynamic_refresh: true
  per_profile: false
items:
- caption: Allow the user to manually disconnect or modify a VPN
  value: true
- caption: Do not allow the user to manually disconnect or modify a VPN
  value: false
owners:
- giovax@chromium.org
schema:
  type: boolean
supported_on:
- chrome_os:71-
tags: []
type: main
