arc_support: This policy has no effect on the logging done by Android.
caption: Report network configuration
default: true
desc: |-
  Report users network configuration on enrolled devices.

        If the policy is set to false, the information will not be reported.
        If set to true or unset, the device's network configuration will be reported.
device_only: true
example_value: false
features:
  dynamic_refresh: true
items:
- caption: Report network configuration
  value: true
- caption: Do not report network configuration
  value: false
owners:
- tylergarrett@google.com
- cros-reporting-team@google.com
schema:
  type: boolean
supported_on:
- chrome_os:96-
tags:
- admin-sharing
type: main
generate_device_proto: False
