caption: Set advanced battery charge mode day config
desc: |-
  If <ph name="DEVICE_ADVANCED_BATTERY_CHARGE_MODE_ENABLED_POLICY_NAME">DeviceAdvancedBatteryChargeModeEnabled</ph> is set to Enabled, then setting <ph name="DEVICE_ADVANCED_BATTERY_CHARGE_MODE_DAY_CONFIG_POLICY_NAME">DeviceAdvancedBatteryChargeModeDayConfig</ph> lets you set up advanced battery charge mode. From <ph name="CHARGE_START_TIME_FIELD_NAME">charge_start_time</ph> until <ph name="CHARGE_END_TIME_FIELD_NAME">charge_end_time</ph>, the device's battery will only be allowed to charge to full once. For the remainder of the period, the batteries are kept in a lower charging state. The value for <ph name="CHARGE_START_TIME_FIELD_NAME">charge_start_time</ph> must be less than <ph name="CHARGE_END_TIME_FIELD_NAME">charge_end_time</ph>.

        Leaving the policy unset keeps advanced battery charge mode off.

        Valid values for <ph name="MINUTE_FIELD_NAME">minute</ph> field in <ph name="CHARGE_START_TIME_FIELD_NAME">charge_start_time</ph> and <ph name="CHARGE_END_TIME_FIELD_NAME">charge_end_time</ph> are 0, 15, 30, 45.
device_only: true
example_value:
  entries:
  - charge_end_time:
      hour: 23
      minute: 0
    charge_start_time:
      hour: 20
      minute: 30
    day: TUESDAY
  - charge_end_time:
      hour: 6
      minute: 45
    charge_start_time:
      hour: 4
      minute: 15
    day: FRIDAY
features:
  dynamic_refresh: true
  per_profile: false
owners:
- bkersting@google.com
- kerker@chromium.org
- chungsheng@google.com
- byronlee@chromium.org
- chromeos-oem-services@google.com
schema:
  properties:
    entries:
      items:
        properties:
          charge_end_time:
            $ref: Time
            description: Time when the device will stop charging, interpreted in the
              device's local time zone.
          charge_start_time:
            $ref: Time
            description: Time when the device will start charging, interpreted in
              the device's local time zone.
          day:
            $ref: WeekDay
        type: object
      type: array
  type: object
supported_on:
- chrome_os:75-
tags: []
type: dict
generate_device_proto: False
