caption: Settings for <ph name="CHROME_DEVTOOLS_NAME">Chrome DevTools</ph> Generative AI Features

desc: |-
  These features in <ph name="CHROME_DEVTOOLS_NAME">Chrome DevTools</ph> employ generative AI models to provide additional debugging information. To use these features, <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> has to collect data such as error messages, stack traces, code snippets, and network requests and send them to a server owned by Google, which runs a generative AI model. Response body or authentication and cookie headers in network requests are not included in the data sent to the server.

  0 = Allow the feature to be used, while allowing Google to use relevant data to improve its AI models. Relevant data may include prompts, inputs, outputs, source materials, and written feedback, depending on the feature. It may also be reviewed by humans to improve AI models. 0 is the default value, except when noted below.

  1 = Allow the feature to be used, but does not allow Google to improve models using users' content (including prompts, inputs, outputs, source materials, and written feedback). 1 is the default value for Enterprise users managed by <ph name="GOOGLE_ADMIN_CONSOLE_PRODUCT_NAME">Google Admin console</ph> and for Education accounts managed by <ph name="GOOGLE_WORKSPACE_PRODUCT_NAME">Google Workspace</ph>.

  2 = Do not allow the feature.

  If the policy is unset, its behavior is determined by the <ph name="GEN_AI_DEFAULT_SETTINGS_POLICY_NAME">GenAiDefaultSettings</ph> policy.

  <ph name="CHROME_DEVTOOLS_NAME">Chrome DevTools</ph> Generative AI features include:

  - Console Insights: explains console messages and offers suggestions on how to fix console errors.

  - AI assistance: get help with understanding CSS styles (since version 131), network requests, performance, and files (all since version 132).

  For more information on data handling for generative AI features, please see https://support.google.com/chrome/a?p=generative_ai_settings.
default: 0
example_value: 2
features:
  dynamic_refresh: true
  per_profile: true
items:
- caption: Allow <ph name="CHROME_DEVTOOLS_NAME">Chrome DevTools</ph> Generative AI Features and improve AI models.
  name: Allowed
  value: 0
- caption: Allow <ph name="CHROME_DEVTOOLS_NAME">Chrome DevTools</ph> Generative AI Features without improving AI models.
  name: AllowedWithoutLogging
  value: 1
- caption: Do not allow <ph name="CHROME_DEVTOOLS_NAME">Chrome DevTools</ph> Generative AI Features.
  name: Disabled
  value: 2
owners:
- wolfi@chromium.org
- devtools-console-insights@google.com
schema:
  enum:
  - 0
  - 2
  - 1
  type: integer
supported_on:
- chrome.*:125-
- chrome_os:125-
tags: []
type: int-enum
