[package]
name = "gnrt"
version = "0.0.0"
edition = "2021"
build = "build/build.rs"

[lib]
name = "gnrt_lib"
path = "lib/lib.rs"

[[bin]]
name = "gnrt"
path = "main.rs"

[dependencies]
anyhow = "1"
cargo-platform = "0.2"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
guppy = "0.17.18"
handlebars = "6.3.2"
itertools = "0.14"
log = { version = "0.4", features = ["std"] }
once_cell = "1"
proc-macro2 = "1.0.103"
reqwest = { version = "0.12", features = ["blocking"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spdx = "0.12.0"
strum = "0.27.1"
strum_macros = "0.27.1"
syn = { version = "2.0.110", features = ["full", "visit"] }
tar = "0.4"
target-spec = "3.4.2"
tempfile = "3"
toml = "0.8"
toml_edit = "0.23.7"

[dependencies.env_logger]
version = "0.11"
default-features = false
features = ["color"]

[build-dependencies]
anyhow = "1.0.97"
heck = "0.5.0"
itertools = "0.14"
prettyplease = "0.2.31"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"

[dev-dependencies]
pretty_assertions = "1.4.1"
