name: android_23.lts.1+

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - '23.lts.1\+'
  push:
    branches:
      - '23.lts.1\+'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  android-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-arm64
      nightly: ${{ github.event.inputs.nightly }}
  android-arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-arm
      nightly: ${{ github.event.inputs.nightly }}
  android-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-x86
      nightly: ${{ github.event.inputs.nightly }}
