name: android

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, ready_for_review]
    branches:
      - main
      - experimental/*
      - feature/*
  push:
    branches:
      - main
      - experimental/*
      - feature/*

jobs:
  chromium_android-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: chromium_android-arm64
  chromium_android-arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: chromium_android-arm
  chromium_android-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: chromium_android-x86
