name: android_24.lts.1+

on:
  release:
    types: [prereleased, released, published]
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, labeled]
    branches:
      - '24.lts.1\+'
  push:
    branches:
      - '24.lts.1\+'
  schedule:
    # GMT timezone.
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  android-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-arm64
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk
  android-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-x86
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk
  android-arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-arm
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk

  upload-release-artifacts:
    runs-on: ubuntu-latest
    needs: [ android-arm, android-arm64, android-x86 ]
    permissions:
      actions: write
    steps:
      - name: Download arm-gold apk
        uses: actions/download-artifact@v4
        with:
          name: android-arm-gold
          path: arm-gold
      - name: Download arm-qa apk
        uses: actions/download-artifact@v4
        with:
          name: android-arm-qa
          path: arm-qa
      - name: Download arm64-gold apk
        uses: actions/download-artifact@v4
        with:
          name: android-arm64-gold
          path: arm64-gold
      - name: Download arm64-qa apk
        uses: actions/download-artifact@v4
        with:
          name: android-arm64-gold
          path: arm64-qa
      - name: Download x86-gold apk
        uses: actions/download-artifact@v4
        with:
          name: android-x86-gold
          path: x86-gold
      - name: Download x86-qa apk
        uses: actions/download-artifact@v4
        with:
          name: android-x86-qa
          path: x86-qa
      - name: 'Upload Android APKs'
        uses: actions/upload-artifact@v4
        with:
          name: Android APKs
          path: ./*
          retention-days: 90
          compression-level: 0 # We expect kept artifacts to be already compressed
          if-no-files-found: error
