name: android_nightly_23.lts.1+

on:
  workflow_dispatch:
  push:
    branches:
      - '23.lts.1\+'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-arm64
  arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-arm
  x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-x86
