name: evergreen_26.eap
permissions: read-all

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - 26.eap
  push:
    branches:
      - 26.eap
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  evergreen-arm-hardfp-rdk:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-hardfp-rdk
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: true
    secrets:
      datadog_api_key: ${{ secrets.DD_API_KEY }}
