name: evergreen

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  schedule:
    # GMT timezone.
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  evergreen-x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-x64
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: false
  evergreen-arm-hardfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-hardfp
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: false
  evergreen-arm-softfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-softfp
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: false
  evergreen-arm-softfp-no-loader:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-softfp-no-loader
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: false
  evergreen-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm64
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: false
  evergreen-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-x86
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: false
