name: evergreen_25.lts.1+

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - '25.lts.1\+'
  push:
    branches:
      - '25.lts.1\+'
  schedule:
    # GMT timezone.
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  evergreen-x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-x64
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: true
  evergreen-arm-hardfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-hardfp
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: true
  evergreen-arm-softfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-softfp
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: true
  evergreen-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm64
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: true
  evergreen-rdk-arm-hardfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-rdk-arm-hardfp
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: true
