name: evergreen_23.lts.1+

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - '23.lts.1\+'
  push:
    branches:
      - '23.lts.1\+'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  evergreen-x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-x64
  evergreen-arm-hardfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-arm-hardfp
  evergreen-arm-softfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-arm-softfp
  evergreen-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-x86
