name: nightly_trigger_main

on:
  schedule:
    # GMT timezone.
    - cron: '0 10,12,14 * * *'
  workflow_dispatch:

jobs:
  trigger_main:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main
          persist-credentials: false
      - name: Trigger Nightly
        run: |
          set -x
          gh workflow run android --ref main -f nightly=true
          gh workflow run linux --ref main -f nightly=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
